# Generated by Django 4.1.7 on 2023-04-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_event_dentista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
    ]
