# Generated by Django 4.1.6 on 2023-02-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_alter_paciente_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('professional', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('professional', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
