# Generated by Django 4.1.7 on 2023-04-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_event_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa',
        ),
    ]
