# Generated by Django 4.1.6 on 2023-02-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_caixa_alter_despesa_date_alter_receita_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receita',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
