# Generated by Django 4.1.7 on 2023-04-04 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_delete_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receita',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
