# Generated by Django 4.1.6 on 2023-02-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0007_remove_despesa_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='desc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
