# Generated by Django 4.1.6 on 2023-03-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0008_alter_despesa_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Cliente',
        ),
    ]
