# Generated by Django 4.1.6 on 2023-03-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0011_alter_cliente_cpf_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
